export const FILTER = 'FILTER';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const ADD_CARD = 'ADD_CARD';
export const REMOVE_CARD = 'REMOVE_CARD';
export const CLEAR_BOARD = 'CLEAR_BOARD';
export const CLEAR_CARDS = 'CLEAR_CARDS';
export const START_EQUITIES = 'START_EQUITIES';
export const GOT_EQUITIES = 'GOT_EQUITIES';
export const EROR_EQUITIES = 'ERROR_EQUITIES';
export const CHANGE_HANDPICKER_MODE = 'CHANGE_HANDPICKER_MODE';
export const VALID_CARDS_SELECTION = 'VALID_CARDS_SELECTION';

